project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  title: "data science for openwashdata"
  description: "Homepage for the course 001"
  site-url: "https://ds4owd-001.github.io/website/"
  
  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "&copy; Copyright 2023, Lars Schöbitz"
    background: "#D9E3E4"
  
  sidebar:
    background: "#D9E3E4"
    logo: "img/logo.png"
    pinned: true
    align: center
    style: "docked"
    search: true
    collapse-level: 1
    tools:
      - icon: github
        href: https://github.com/ds4owd-001
        text: "GitHub organization"
      - icon: code-square
        href: https://posit.cloud/
        text: "Posit Cloud"
    contents: 
      - href: index.qmd
        text: Course Overview
      - text: "---"
      - href: modules/md-01.qmd
        text: Module 1
        
format:
  html:
    theme: cosmo
    css: styles.css
    code-copy: true
    code-overflow: wrap
    toc: true

execute: 
  freeze: auto

