project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  title: "data science for openwashdata"
  description: "Website for data science for openwashdata course 001"
  site-url: "https://ds4owd-001.github.io/website/"
  repo-url: "https://github.com/ds4owd-001"
  favicon: "img/OWD-logo-18.png"
  search: false
  page-footer: 
    left: | 
        This course is part of the [openwashdata project](https://openwashdata.org/) supported by the 
        [Open Research Data Program of the ETH Board](https://ethrat.ch/en/eth-domain/open-research-data/)
    right:
      - text: Code of Conduct
        href: code_of_conduct.qmd
      - icon: "envelope-at"
        href: "mailto:ghe@mavt.ethz.ch?subject=ds4owd support"
        aria-label: Email
      - icon: github
        href: https://github.com/ds4owd-001
        aria-label: GitHub
      - icon: chat-left-dots
        href: https://matrix.to/#/#openwashdata-lobby:staffchat.ethz.ch
        aria-label: Matrix
  
  sidebar:
    background: "#C8CEF3"
    logo: "img/OWD-logo-20.png"
    logo-alt: "openwashdata logo."
    pinned: true
    align: center
    style: "docked"
    search: true
    collapse-level: 1
    tools:
      - icon: github
        href: https://github.com/ds4owd-001
        text: "GitHub organization"
    contents: 
      - href: index.qmd
        text: Sign-up here
      - text: "---"
      - href: overview.qmd
        text: Course Overview
      - href: calendar.qmd
        text: Course Calendar
      - text: "---"
      - href: modules/md-01.qmd
        text: Module 1
      - href: modules/md-02.qmd
        text: Module 2
      - href: modules/md-03.qmd
        text: Module 3
      - href: modules/md-04.qmd
        text: Module 4
      - href: modules/md-05.qmd
        text: Module 5
      - href: modules/md-06.qmd
        text: Module 6
      - href: modules/md-07.qmd
        text: Module 7
      - href: modules/md-08.qmd
        text: Module 8
      - href: modules/md-09.qmd
        text: Module 9
      - href: modules/md-10.qmd
        text: Module 10
format:
  html:
    theme:
      light: [litera, theme.scss]
    highlight-style: a11y-dark
    css: styles.css
    code-copy: true
    code-overflow: wrap
    toc: true
    mainfont: "Atkinson Hyperlegible"
    grid:
      sidebar-width: 250px
      body-width: 900px
      margin-width: 300px
    include-in-header: 
        - text: |
            <script defer data-domain="ds4owd-001.github.io/website" src="https://plausible.io/js/script.js"></script>

execute: 
  freeze: auto

