project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  title: "CVEN 5999 - Summer 2025"
  description: "Homepage for Special Topics - Data Analytics for Development"
  site-url: "https://cven5999-ss25.github.io/website/"
  
  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "&copy; Copyright 2025, Lars Schöbitz"
    background: "#D9E3E4"
  
  sidebar:
    background: "#D9E3E4"
    logo: "img/logo.png"
    pinned: true
    align: center
    style: "docked"
    search: true
    collapse-level: 1
    tools:
      - icon: github
        href: https://github.com/cven5999-ss25
        text: "GitHub organization"
    contents: 
      - href: index.qmd
        text: Course Overview
      - text: "---"
      - href: weeks/wk-01.qmd
        text: "Week 1"
      - href: weeks/wk-02.qmd
        text: "Week 2"
      - href: weeks/wk-03.qmd
        text: "Week 3"
      - href: weeks/wk-04.qmd
        text: "Week 4"
      - href: weeks/wk-05.qmd
        text: "Week 5"
      - href: weeks/wk-06.qmd
        text: "Week 6"
      - text: "---"
      - href: "project/index.qmd"
        text: "Capstone Project"
        

format:
  html:
    theme:
      light: [litera, theme.scss]
    code-copy: true
    code-overflow: wrap
    link-external-icon: true
    link-external-newwindow: true
    toc: true
    mainfont: "Atkinson Hyperlegible"
    include-in-header:
        - text: |
            <script defer data-domain="cven5999-ss25.github.io/website/" src="https://plausible.io/js/script.js"></script>

freeze: auto
editor: source